Align files (#1151)
* K8s 1.25 (#1122)

* k8s 1.25 support

* k8s 1.25 support

* check calico crd exists before installing calico

* bump calico manifests

* bump calico manifests

* bump calico manifests

* bump calico manifests

* bump calico manifests

* Release v17.0.0 (#1123)

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

* Remove usage of `--logtostderr` flag that was removed upstream since 1.26. (#1124)

* Remove CSIMigration feature flag (#1126)

* remove csimigration flag

* Update CHANGELOG.md

* Enable auditd systemd unit (#1133)

* Move pull request template into .github (#1137)

Towards https://github.com/giantswarm/giantswarm/issues/27797 - This PR moves the PR template into the canonical location .github/pull_request_template.md, to reserve the docs/ folder purely for documentation.

* Fix CircleCI badge in README (#1138)

* Align files (#1077)

Co-authored-by: github-actions <action@github.com>

* Align files (#1145)

Co-authored-by: github-actions <action@github.com>

* Align files

---------

Co-authored-by: Christian Bianchi <whites11@gmail.com>
Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Co-authored-by: Nick Jüttner <nick@giantswarm.io>
Co-authored-by: Quentin Bisson <quentin@giantswarm.io>
Co-authored-by: Marian Steinbach <marian@giantswarm.io>
Co-authored-by: github-actions <action@github.com>

diff --git a/files/conf/k8s-addons b/files/conf/k8s-addons
--- a/files/conf/k8s-addons
+++ b/files/conf/k8s-addons
@@ -26,7 +26,6 @@ done
 SECURITY_FILES=""
 SECURITY_FILES="${SECURITY_FILES} rbac_bindings.yaml"
 SECURITY_FILES="${SECURITY_FILES} rbac_roles.yaml"
-SECURITY_FILES="${SECURITY_FILES} psp_policies.yaml"
 SECURITY_FILES="${SECURITY_FILES} psp_roles.yaml"
 SECURITY_FILES="${SECURITY_FILES} psp_binding.yaml"
 
@@ -81,26 +80,33 @@ kubectl delete pods -l app.kubernetes.io/name=kube-proxy -n kube-system
 {{ end }}
 
 {{ if not .DisableCalico }}
-# install calico CRDS
-PROXY_MANIFESTS="calico-crd-installer-rbac.yaml calico-crd-installer.yaml"
-for manifest in $PROXY_MANIFESTS
+while ! kubectl get crd ippools.crd.projectcalico.org
 do
-    while
-        kubectl apply -f /srv/$manifest
-        [ "$?" -ne "0" ]
-    do
-        echo "failed to apply /srv/$manifest, retrying in 5 sec"
-        sleep 5s
-    done
-done
-echo "calico CRD installer successfully applied"
+  echo "Ensuring calico CRDs."
 
-while
-    kubectl wait --for=condition=complete --timeout=1m -n kube-system job -lapp.kubernetes.io/name=calico-crd-installer
-    [ "$?" -ne "0" ]
-do
-    echo "Failed waiting for crd installer job to be completed, retrying in 5 sec"
-    sleep 5s
+  # install calico CRDS
+  PROXY_MANIFESTS="calico-crd-installer-rbac.yaml calico-crd-installer.yaml"
+  for manifest in $PROXY_MANIFESTS
+  do
+      while
+          kubectl apply -f /srv/$manifest
+          [ "$?" -ne "0" ]
+      do
+          echo "failed to apply /srv/$manifest, retrying in 5 sec"
+          sleep 5s
+      done
+  done
+  echo "calico CRD installer successfully applied"
+
+  while
+      kubectl wait --for=condition=complete --timeout=1m -n kube-system job -lapp.kubernetes.io/name=calico-crd-installer
+      [ "$?" -ne "0" ]
+  do
+      echo "Failed waiting for crd installer job to be completed, retrying in 5 sec"
+      sleep 5s
+  done
+
+  echo "Calico CRD job completed successfully"
 done
 
 {{ if .CalicoPolicyOnly }}
