Setup aws-cni before calico

diff --git a/files/conf/k8s-addons b/files/conf/k8s-addons
--- a/files/conf/k8s-addons
+++ b/files/conf/k8s-addons
@@ -88,6 +88,33 @@ echo "kube-proxy successfully installed"
 # restart ds to apply config from configmap
 kubectl delete pods -l app.kubernetes.io/name=kube-proxy -n kube-system
 
+{{ if .EnableAWSCNI -}}
+## Apply AWS VPC CNI
+CNI_FILE="aws-cni.yaml"
+
+for manifest in ${CNI_FILE}
+do
+    while
+        kubectl apply -f /srv/$manifest
+        [ "$?" -ne "0" ]
+    do
+        echo "failed to apply /srv/$manifest, retrying in 5 sec"
+        sleep 5s
+    done
+done
+
+while
+    echo "Waiting for aws-node to be ready..."
+    kubectl -n kube-system -l app.kubernetes.io/name=aws-node wait --for=condition=Ready --timeout=1m pods
+    [ "$?" -ne "0" ]
+do
+    echo "aws-node was not ready after 1 minute"
+done
+
+echo "aws-node is ready"
+
+{{ end -}}
+
 # TODO: remove migrator once all clusters have been migrated to kubernetes datastore
 kubectl apply -f /srv/calico-crd-installer-rbac.yaml
 for job in calico-crd-installer calico-datastore-migrator-pre
@@ -99,10 +126,6 @@ done
 {{ if .CalicoPolicyOnly -}}
 ## Apply Calico with network policy features only
 CNI_FILE="calico-policy-only.yaml"
-{{ if .EnableAWSCNI -}}
-## Apply AWS VPC CNI
-CNI_FILE="aws-cni.yaml"
-{{ end -}}
 {{ else -}}
 ## Apply Calico with all its components
 CNI_FILE="calico-all.yaml"
