ensure namespaces exist (needed in clusters where the app-operator is not running) (see https://github.com/giantswarm/k8scloudconfig/pull/609)

diff --git a/v_5_0_0/files/conf/k8s-addons b/v_5_0_0/files/conf/k8s-addons
--- a/v_5_0_0/files/conf/k8s-addons
+++ b/v_5_0_0/files/conf/k8s-addons
@@ -9,6 +9,21 @@ KUBECTL={{ .RegistryDomain }}/giantswarm/docker-kubectl:f5cae44c480bd797dc770dd5
 # wait for healthy master
 while [ "$(/usr/bin/docker run -e KUBECONFIG=${KUBECONFIG} --net=host --rm -v /etc/kubernetes:/etc/kubernetes $KUBECTL get cs | grep Healthy | wc -l)" -ne "3" ]; do sleep 1 && echo 'Waiting for healthy k8s'; done
 
+# ensure namespaces exist (needed in clusters where the app-operator is not running)
+NAMESPACES="giantswarm"
+for namespace in ${NAMESPACES}
+do
+    if ! /usr/bin/docker run -e KUBECONFIG=${KUBECONFIG} --net=host --rm -v /etc/kubernetes:/etc/kubernetes $KUBECTL get namespaces ${namespace} ; then
+        while
+            /usr/bin/docker run -e KUBECONFIG=${KUBECONFIG} --net=host --rm -v /etc/kubernetes:/etc/kubernetes $KUBECTL create namespace ${namespace}
+            [ "$?" -ne "0" ]
+        do
+            echo "failed to create namespace ${namespace}, retrying in 5 sec"
+            sleep 5s
+        done
+    fi
+done
+
 # label namespaces (required for network egress policies)
 NAMESPACES="default kube-system" 
 for namespace in ${NAMESPACES}
