fix bugs1

diff --git a/v_5_2_0/files/conf/k8s-addons b/v_5_2_0/files/conf/k8s-addons
--- a/v_5_2_0/files/conf/k8s-addons
+++ b/v_5_2_0/files/conf/k8s-addons
@@ -96,12 +96,15 @@ CNI_FILE="aws-cni.yaml calico-policy-only.yaml"
 CNI_FILE="calico-all.yaml"
 {{ end -}}
 
-while
-    $KUBECTL apply -f /srv/$CNI_FILE
-    [ "$?" -ne "0" ]
+for manifest in ${CNI_FILE}
 do
-    echo "failed to apply /srv/$manifest, retrying in 5 sec"
-    sleep 5s
+    while
+        $KUBECTL apply -f /srv/$manifest
+        [ "$?" -ne "0" ]
+    do
+        echo "failed to apply /srv/$manifest, retrying in 5 sec"
+        sleep 5s
+    done
 done
 
 {{ if eq .Cluster.Kubernetes.CloudProvider "aws" -}}
