Add giantswarm priority class

diff --git a/v_4_0_0/files/conf/k8s-addons b/v_4_0_0/files/conf/k8s-addons
--- a/v_4_0_0/files/conf/k8s-addons
+++ b/v_4_0_0/files/conf/k8s-addons
@@ -69,6 +69,17 @@ else
     echo "no default storage class to apply"
 fi
 
+# apply calico
+PRIORITY_CLASSES_FILE="priority_classes.yaml"
+
+while
+    /usr/bin/docker run -e KUBECONFIG=${KUBECONFIG} --net=host --rm -v /srv:/srv -v /etc/kubernetes:/etc/kubernetes $KUBECTL apply -f /srv/$PRIORITY_CLASSES_FILE
+    [ "$?" -ne "0" ]
+do
+    echo "failed to apply /srv/$manifest, retrying in 5 sec"
+    sleep 5s
+done
+
 # apply k8s addons
 MANIFESTS=""
 {{ range .ExtraManifests -}}
