Align latest changes

diff --git a/v_4_0_0/files/conf/k8s-addons b/v_4_0_0/files/conf/k8s-addons
--- a/v_4_0_0/files/conf/k8s-addons
+++ b/v_4_0_0/files/conf/k8s-addons
@@ -2,7 +2,7 @@
 
 export KUBECONFIG=/etc/kubernetes/config/addons-kubeconfig.yaml
 # kubectl 1.8.4
-KUBECTL={{ .RegistryDomain }}/giantswarm/docker-kubectl:8cabd75bacbcdad7ac5d85efc3ca90c2fabf023b
+KUBECTL={{ .RegistryDomain }}/giantswarm/docker-kubectl:f5cae44c480bd797dc770dd5f62d40b74063c0d7
 
 /usr/bin/docker pull $KUBECTL
 
@@ -27,6 +27,19 @@ do
         sleep 5s
     done
 done
+
+PROXY_MANIFESTS="kube-proxy-sa.yaml kube-proxy-ds.yaml"
+for manifest in $PROXY_MANIFESTS
+  do
+    while
+      /usr/bin/docker run -e KUBECONFIG=${KUBECONFIG} --net=host --rm -v /srv:/srv -v /etc/kubernetes:/etc/kubernetes $KUBECTL apply -f /srv/$manifest
+      [ "$?" -ne "0" ]
+    do
+      echo "failed to apply /srv/$manifest, retrying in 5 sec"
+      sleep 5s
+    done
+  done
+echo "kube-proxy successfully installed"
 
 {{ if not .DisableCalico -}}
 
@@ -85,8 +98,6 @@ MANIFESTS=""
 {{ range .ExtraManifests -}}
 MANIFESTS="${MANIFESTS} {{ . }}"
 {{ end -}}
-MANIFESTS="${MANIFESTS} kube-proxy-sa.yaml"
-MANIFESTS="${MANIFESTS} kube-proxy-ds.yaml"
 MANIFESTS="${MANIFESTS} coredns.yaml"
 {{ if not .DisableIngressController -}}
 MANIFESTS="${MANIFESTS} default-backend-dep.yaml"
